### ISSUE TITLE
Can you please provide complete example

### ISSUE THREAD

**Issue by vtahlani** [DxCx/graphql-rxjs#22]
Can you please provide end to end example, in current example query is hard coded and output is written on console. Do you have example where I can pass query from client(similar to graphiQL) and send response back to client only?

We use  below for graphql to start server at 4000 and inbuilt client(graphiql).
`const app = express();

app.use(graphQLHTTP({
    schema,
    graphiql:true,
}));

app.listen(4000);`

**Comment by DxCx** [comment]
hey @vtahlani ,
because GraphQL had changed alot since may 2017, i decided to hold this and let it be more stable
and then rewrite this in a better way.
I've started the rewrite those days, will update when i have something more concrete...

Anyway, this is just the graphql engine,
you will need to use some server package in order to use it over the network, for example apollo's websocket transport.

**Comment by vtahlani** [comment]
I tried subscription using graphql and  graphql-subscriptions but it is not working. Below is what i have tried, do you know what is missing here?

======subcritionSchema.js======================
import {
  GraphQLList,
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString,
} from 'graphql';

import { subscribe, createSourceEventStream } from 'graphql/subscription';

import { PubSub } from 'graphql-subscriptions';


const pubsub = new PubSub();

const SOMETHING_CHANGED_TOPIC = 'somethingChanged';

pubsub.publish(SOMETHING_CHANGED_TOPIC, { somethingChanged: { id: "123" }});


const Result = new GraphQLObjectType({
    name: 'testFields',
    fields: () => ({
        id: {
            description: 'enter your description',
            type: GraphQLString
        }
    })
});

const subscriptionType = new GraphQLObjectType({
    name: 'Subscription',
    description: 'The root of all queries',
    fields: () => ({
        somethingChanged:{
            type: Result,
            subscribe: () => pubsub.asyncIterator(SOMETHING_CHANGED_TOPIC)
         },
    }),
});

const queryType = new GraphQLObjectType({
    name: 'Query',
    description: 'The root of all queries',
    fields: () => ({
         test:{
            type: GraphQLString,
            resolve: (root, args) => "TEST"
         },
    }),
});

export default new GraphQLSchema({
    query:queryType,
    subscription: subscriptionType,
});

==================server.js=======
import express from 'express';
import graphQLHTTP from 'express-graphql';
import schema from './subscriptionSchema';
import graphql from 'graphql';

const app = express();

app.use(graphQLHTTP({
    schema,
    graphiql:true,
}));

app.listen(4000);
=======================

when i query from GraphiQL i don't get any data

query 
subscription{
  somethingChanged {
    id
  }
}

response
{
  "data": {
    "somethingChanged": null
  }
}

**Comment by DxCx** [comment]
hey @vtahlani 
i've just released the updated package,
i'm waiting for last patch to be merged to apollo's graphiql renderer then i'll post an example repository that is using:
 - graphql-rxjs
 - subscription-transport-ws (graphql-transport-ws)
 - apollo-server-express (for graphiql)

**Comment by DxCx** [comment]
hey @vtahlani 
I've just uploaded a simple example over websocket:
https://github.com/DxCx/graphql-rxjs-websocket-example

enjoy

**Comment by vtahlani** [comment]
Hi @DxCx,
Thanks for your help. I tried the example, server starts and when i send query i get proper response, however when i send request for subscription i get response as [object,object] and sometime get "Your subscription data will appear here after server publication" which is coming from https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/blob/master/src/fetcher.ts

Can you please let me know why i am getting subscription response as [object,object], am i missing anything?

Get graphiql UI using url http://localhost:5000/graphiql
send request as "subscription{clock}"
got response as [object,object]

**Comment by vtahlani** [comment]
It works when i send request on graphql end point with POST.

curl -X POST -H "Content-Type:application/graphql" -d '{"query":"subscription{clock}"}' http://localhost:5000/graphql

response
{
    "data": {
        "clock": "Thu Aug 03 2017 16:07:53 GMT+0530 (India Standard Time)"
    }
}

**Comment by DxCx** [comment]
hey @vtahlani you are not using full websocket..
please make sure HYBRID under src/main.ts is `false`. then you can use `/graphiql`;

the reason you got [object] is that apollo-server (http) is not running graphql-rxjs but graphql.
i'll try to open a PR in the future to allow different graphql implementations on the server..

anyway, on hybrid mode you will need to use `/graphiql-full`

**Comment by vtahlani** [comment]
You are running websocket server, right? If I send request using websocket
client for Smart websocket client(chrome extention) those are also not
working.

**Comment by DxCx** [comment]
Yes, this is websocket server, ypu should be able to connect with any client, but you will need to implement the graphql websocket spec.
The spec is found under the repository of 'subscription-transport-ws' or you can just use the client there..

**Comment by vtahlani** [comment]
Only /graphql works both graphiql and graphiql-full(in hybrid) not working.

**Comment by vtahlani** [comment]
If it is fine, can you please share your client as well which you used to test subscription so i will have same end to end example.

Non Hybrid mode
1.1) /graphiql  from browser open graphiql but give response as [object,object]
1.2) /graphql from browser returns gives error

from postmen
2.1) /graphiql gives error with http post method
2.2) /graphql gives data but again [Object,Object]
{
   data:{
       clock : [object,object] 
   }
}

Both 1.1 and 2.2 return response as [Object,Object] only but later has response inline with graphql response.

**Comment by DxCx** [comment]
Which browser are ypu using? Is it supporting websocket natively?

**Comment by vtahlani** [comment]
I am using Chrome and "Smart WebSocket client" chrome extention but not working from both

**Comment by vtahlani** [comment]
Tried to write my own websocket client as mentioned here https://github.com/apollographql/subscriptions-transport-ws but get error subscribeToMore function not found.

`const { SubscriptionClient,addGraphQLSubscriptions } = require('subscriptions-transport-ws');
import ApolloClient,{createNetworkInterface} from 'apollo-client';
import ws from 'ws';
import gql from 'graphql-tag';
 
const GRAPHQL_ENDPOINT = 'ws://localhost:5000/graphiql';
 
 const networkInterface = createNetworkInterface({
 uri: 'http://localhost:5000/graphql' // Your GraphQL endpoint
});

const client = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true,
},ws);

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    client
);
 
const apolloClient = new ApolloClient({
    networkInterface: networkInterfaceWithSubscriptions,
});


apolloClient.subscribe({
  query: gql`
        subscription{ click 
        }`,
    variables: {},
});
`
If is use subscribe instead of subscribeTomore then it works but don't know how to get response after using subscribe.
