### ISSUE TITLE
mutation resolver to return asynciterator

### ISSUE THREAD

**Issue by veeramarni** [DxCx/graphql-rxjs#30]
I have a case where I need to run a train of actions with a mutation call and update the client on each step completion. 

For example 
1. client requested to create and start an action (mutation call)
2. mutation calls a service and the service should update the client when each action completes. So I think asynciterator is the best fit. Do you think `graphql-rxjs` fits the case? What do you suggest would be a better way to do it.

Below is just base line for what i want to achieve. 

```
public async updateAction(request): AsyncIterator<IAction> {
cons action = await this.writeToDatabase(request). 
// udpate the client that request is persisted and action is in pending
const createAction = // some async action to create task
// update client that action is created
const startAction = // some async action to start task
// update client that action is started. 
finally return
```

I know this can be achieved with subscription, but I feel we don't have use subscription since the data feed would only go to one client during the series of these action.

**Comment by DxCx** [comment]
Hey @veeramarni,
By definition, mutations are running serially and will wait for latest field to complete before evaluating next field.
