### ISSUE TITLE
@live sending the whole payload instead of just sending the change

### ISSUE THREAD

**Issue by shtse8** [DxCx/graphql-rxjs#39]
Note that the latest release of @live will send the whole payload instead of just the live attribute. Is it by design or just a bug? It's better to send the change only due to the whole payload could be large (>100kb).

**Comment by DxCx** [comment]
hey @shtse8 ,
graphql-rxjs is just an engine to enable reactive responses.
what you are want is a network feature.
the idea is to create immutable responses from the engine,
diffing them against last response
and make them immutable again on client

there was a plan to add support for that on `subscription-transport-ws` for diffing & patching but it wasn't done yet.

**Comment by shtse8** [comment]
Got it, thanks for your explanation.
