### ISSUE TITLE
Make compatible with Apollo Link

### ISSUE THREAD

**Issue by smkhalsa** [DxCx/graphql-rxjs#40]
I'm trying to create a custom Apollo Link to use with Apollo Client. However, I'm running into an issue that I believe has to do with the differences between RxJS and zen-observable (used by apollo). Here's my Apollo Link:

```
import { ApolloLink, Operation, FetchResult, Observable } from 'apollo-link'
import { graphqlRx } from 'graphql-rxjs'
import { print } from 'graphql/language/printer'

export class LocalLink extends ApolloLink {
  constructor({ schema, rootValue, context }) {
    super()

    this.schema = schema
    this.rootValue = rootValue
    this.context = context
  }

  request(operation) {
    const request = {
      ...operation,
      query: print(operation.query)
    }

    return Observable.from(graphqlRx(
      this.schema,
      request.query,
      this.rootValue,
      this.context,
      request.variables,
      request.operationName
    ))
  }
}

export default LocalLink
```

However, I'm getting the following error: 

```
Error: Network error: Observable.Observable.fromPromise(...).flatMap is not a function
```

**Comment by DxCx** [comment]
hey @smkhalsa sorry for the delay response, missed this issue with all of my gh notifications.. =\

GraphQL-RxJs is compatible with Apollo-Link & Apollo client 2
however, you are using it wrong here. (unless you meant to use it only client side and that is not tested by me yet, but adding support is not so hard at all)

What you need to do is to setup websocket transport (subscription-transport-ws) and bind graphql-rxjs to it. an example can be found here (https://github.com/DxCx/graphql-rxjs-websocket-example)

once done, just connect your apollo client to it by creating subscription-transport-ws client
and send it as a param to apollo-link.

let me know if that works or you have more issues.

**Comment by loganpowell** [comment]
Hi @DxCx ! Super excited to see this thread. I'm looking for a way to use RxJS and Apollo link/client together on the client. I'm super new to RxJS and am equally confused about how to use the 'observables' emitted from `apollo-link`. I would assume that there would be more examples out there, but perhaps they're spreading themselves too thin these days (trying to unseat the other state management solutions, e.g.).

Might you have any examples/guidance for how to use `graphql-rxjs` on the client?

**Comment by DxCx** [comment]
Yeah you have the example ive shared above for servers

To make it work with apollo link just use the standard ws link with ws:// prefix
